name: ci

on:
  push:
    branches:
      - 'main'

env:
  DEV_IMAGE: ph1t0/defi-dev:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DEV_IMAGE }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.DEV_IMAGE }} brownie test
